services:

  backend_admin:
    build: .
    command: python manage.py runserver 0.0.0.0:5050
    volumes:
      - .:/app
    ports:
      - "5050:5050"
      
  admin_celery:
    build: .
    command: celery -A project_core worker --loglevel=INFO

  admin_queue:
    build: .
    command: python consumer.py